### PR TITLE
Enable Selinux Enforcing

### PR DESCRIPTION
**Pull request by zimmerry**

### CODE REVIEW

**Comment by zimmerry** [comment]
[Enable SELinux Enforcing](https://trello.com/c/WlALaNKE/930-enable-selinux-enforcing)

**Review by ramereth — APPROVED** [review]
Patch bump please.

**Comment by zimmerry** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v3.3.1.  Have a nice day!

**Pull request merged**
