### PR TITLE
Add support for AlmaLinux 9

### PR DESCRIPTION
**Pull request by sharoninator**

### CODE REVIEW

**Review by ramereth — CHANGES_REQUESTED** [review]
Add AlmaLinux 9 to unit testing, see `spec/spec_helper.rb`

**Comment by sharoninator** [comment]
How's this?

**Comment by ramereth** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v4.3.1.  Have a nice day!

**Pull request merged**
